# fly.toml app configuration file generated for mems-22xa-g on 2026-07-26T01:08:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mems-22xa-g'
primary_region = 'lhr'

[build]

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'

[[mounts]]
  source = 'bearhunt_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
