app = "bearhunt"
primary_region = "iad"

[build]

[[mounts]]
source = "bearhunt_data"
destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
